### ISSUE TITLE
Cannot hide GPA as it is hardcoded in the template

### ISSUE THREAD

**Issue by geogeek11** [feder-cr/lib_resume_builder_AIHawk#20]
I have tried to customize the css style in order to hide the GPA score as it is not useful all the cases, but the GPA is not isolated in a dedicated tag.

So how could I change the HTML template ?

is there any projected HTML template change in the future versions ?

**Comment by feder-cr** [comment]
@geogeek11 check now, i canghe the template

**Comment by geogeek11** [comment]
Sorry may be I was not clear enough.
I mean to split this tag into 2 tags
`<span class="entry-title">[Degree] in [Field of Study] | Grade: [Your Grade]</span>`
Like in the line below:
`<span class="entry-title">[Degree] in [Field of Study]</span> <span class="entry-grad"> | Grade: [Your Grade]</span>`
so I can hide .entry-grad if not needed

**Comment by feder-cr** [comment]
Sorry, I can't!
